Mayuresh-22/Minglr

style/style.css

Added hover effects when we navigate to the tabs at the top for better UX

---

index.php

Enhance the functionality of Index.php to automatically route authenticated users to the feed page upon successful login.

Update Index.php to redirect user on feed page after login.

---

about-us.php
account.php
feed.php
index.php
message.php
style/style.css

Implemented comprehensive enhancements to the navigation bar, resulting in a significantly more elegant and visually pleasing appearance on all pages.

Enhanced navigation bar styling for a more elegant look.

---

about-us.php
account.php
feed.php
index.php
message.php

added favicon to about-us, account, feed, index and messages page

added favicon

---

about-us.php
account.php
feed.php
index.php
js/script.js
message.php
style/style.css

This pull request addresses issue #38 
Before: 
After:

update check button feature

---

account.php
style/account.css

I have ensured the responsiveness of the button in all the three versions of mobile view via media query.

Send-message button made responsive

---

account.php
style/style.css

The title saying mnglr and the three button menu bar are now responsive

Made title bar responsive

---

back/logout.php

Fixed the Logout Functionality of Minglr.

Fixing Logout Functionality

---

style/style.css

The following hovers have been added

added hover effects

---

back/logout.php
db/validate.php
post.php
pvtmsg.php

close #26 
hey @Mayuresh-22 , I Improved Code Formatting for Enhanced Readability. Please review it. Thank you.

formated phpcode

---

account.php
back/logout.php
db/validate.php
post.php
pvtmsg.php

close #36 
Added cursor pointer

Fix cursor pointer

---

style/style.css

**What does this PR do ?**
This PR enhances the UI of the footer section by changing it's color.
Fixes #55 
**Type of change**
UI enhancement
**How should this be tested ?**
**Screenshot of the change**

Feat: Enhanced the UI of the footer by changing it's color

---

message.php

The title and the three button menu bar are now responsive on the message page under issue #42

Made message page responsive

---

account.php
feed.php
style/feed.css

Bug Fix :  Issue #48 
Photos not visible in photos section of the account.

Fixed photos section BUG

---

account.php
feed.php
style/feed.css

I have fixed the height of image in accounts and feed section and also aligned the images as suggested by you. 
Closes #47

Fixed size of uploaded images in feeds and accounts sections

---

about-us.php
account.php
feed.php
index.php
message.php
style/style.css

1) Added Social Media Icons above the navigation links in the footer
2) Changed the colour of the text, "This website is only for educational purposes..." to white to make it more readable on the blue background.

Fixing potential changes to footer for improved user experience 67

---

db/validate.php
index.php
style/style.css

#77 
- added javascript function to handel the regex pattern check .
- if pattern is correct then border color will turn to green else red.
- added icons and description about pattern for similicity
- added show password button
- made some changes in styles.css
- update regex in validate.php to handel specialcase too
Password Regex: `'/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/'`
(Added support for special characters)
Refer thread: #64

[feat] Added password validation on Registration form. Solved #77

---

about-us.php
account.php
feed.php
index.php
message.php
style/style.css

Footer Styling Done

---

back/search.php
index.php

close #100 
I have made autocomplete off.

Changes done for issue: #100

---

README.md

Chore : Update README.md ✅

---

account.php
feed.php
js/script.js
style/style.css

This PR closed issue #111 
Added lightbox effect so the image pops up, an update has been done please check and confirm
updated cursor as well as image lightbox  image effects

[feat] Added lightbox effect so the image get popped up
